# Generated by Django 5.2.8 on 2026-03-15 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restourant_app', '0002_dish_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
