# Generated by Django 5.2.8 on 2026-03-21 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restourant_app', '0007_rename_profile_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
