# Generated by Django 5.2.8 on 2026-03-21 10:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restourant_app', '0008_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='stars',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='food',
            name='stars',
            field=models.FloatField(default=5.0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
