# Generated by Django 5.2.8 on 2026-04-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0002_food_image_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='food_type',
            field=models.CharField(default='Other', max_length=200),
        ),
    ]
