# Generated by Django 5.2.8 on 2026-05-02 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0003_food_food_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='country',
            field=models.CharField(default='innational', max_length=200),
        ),
    ]
