# Generated by Django 5.2.8 on 2026-06-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0004_food_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='country_en',
            field=models.CharField(default='innational', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='country_ru',
            field=models.CharField(default='innational', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='country_uk',
            field=models.CharField(default='innational', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='description_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='food_type_en',
            field=models.CharField(default='Other', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='food_type_ru',
            field=models.CharField(default='Other', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='food_type_uk',
            field=models.CharField(default='Other', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='name_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='name_uk',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
